export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const FETCH_PAYMENTS = "FETCH_PAYMENTS";
export const FETCH_PAYMENT  = "FETCH_PAYMENT";
export const EDIT_PAYMENT   = 'EDIT_PAYMENT';
export const DELETE_PAYMENT = 'DELETE_PAYMENT';
